### ISSUE TITLE
Missing JavaDoc

### ISSUE THREAD

**Issue by echawk** [s-gannon/BestPaint#4]
The following methods do *not* have JavaDoc: (CleanerCanvasTools.java)
         
* getColor()
* getCurrentTool()
* getLineWitdth()

**Comment by s-gannon** [comment]
It is in the process of being fixed. Check back when 0.3.0 rolls out

**Comment by ejyager00** [comment]
Why did you delete my **_comment_**?

**Comment by s-gannon** [comment]
Deleted for harassment
